before_script:
  - apt-get update
  - apt-get install tree -y

build:
  image: golang
  script:
    - mkdir -p $GOPATH/ssurenr
    - cp -r /builds/ssurenr/ $GOPATH/src/ssurenr/
    - cd $GOPATH/src/ssurenr/hfgo/ch01/code-magnet
    - go build